apiVersion: v1
kind: Secret
metadata:
  name: account.owncloud
  labels:
    xdpin.cn/account: "owncloud"
    xdpin.cn/managed-by: "xdpin"
type: kubernetes.io/basic-auth
stringData:
  dbuser: aoxn
  password: Admin123456
  ocpassword: admin
---
apiVersion: v1
data:
  config: |
    acl:
      aclID: acl-j6c9axxwagt5wfbsdgzhn
      auth:
        accessKeyID: AAAAA
        accessKeySecret: AAAAA
        description: kubernetes.aoxn
        region: cn-hongkong
      provider: upnp
    dns:
      auth:
        accessKeyID: AAAAA
        accessKeySecret: AAAAA
        description: com
        region: cn-hangzhou
      domainName: xdpin.cn
      domainRR: '@,www'
      provider: upnp
    mapping:
    - description: ssh
      externalPort: 22
      internalPort: 22
      protocol: TCP
    - description: qBittorrent
      externalPort: 8081
      internalPort: 8081
      protocol: TCP
    - description: jellyfin
      externalPort: 8096
      internalPort: 8096
      protocol: TCP
    - description: stable diffusion
      externalPort: 7860
      internalPort: 7860
      protocol: TCP
    - description: apache ownCloud
      externalPort: 9000
      internalPort: 9000
      protocol: TCP
    - description: kubernetes
      externalPort: 6443
      internalPort: 6443
      protocol: TCP
    securityGroup:
      auth:
        accessKeyID: AAAA
        accessKeySecret: AAAAAA
        description: nnnn
        region: cn-hongkong
      provider: upnp
      ruleIdentity: corp002
      securityGroupID: sg-j6cclf55wiurtiqo3yi3
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-05T03:35:55Z"
  labels:
    xdpin.cn/config: ""
    xdpin.cn/managed-by: "xdpin"
  name: xdpin.cfg
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: account.palworld
  namespace: default
  labels:
    xdpin.cn/account: palworld
    xdpin.cn/managed-by: xdpin
type: Opaque
stringData:
  rconPassword: admin
---
kind: Secret
apiVersion: v1
metadata:
  labels:
    xdpin.cn/account: infra
    xdpin.cn/managed-by: xdpin
  name: account.infra
  namespace: kube-system
stringData:
  access_key_id: "123"
  access_key_secret: "456"
  account_id: infra
  description: aoxn
  provider: alibaba
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-cm
  labels:
    xdpin.cn/config: palworld
    xdpin.cn/managed-by: xdpin
data:
  PUID: "1000"
  PGID: "1000"
  PORT: "8211"  # Optional but recommended
  PLAYERS: "16"  # Optional but recommended
  SERVER_PASSWORD: "worldofpals"  # Optional but recommended
  MULTITHREADING: "true"
  RCON_ENABLED: "true"
  RCON_PORT: "25575"
  TZ: UTC
  COMMUNITY: "false"  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
  SERVER_NAME: "World of Pals"
  SERVER_DESCRIPTION: ""
