---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-meridian-meridian-io-v1-cluster
  failurePolicy: Fail
  name: mcluster.kb.io
  rules:
  - apiGroups:
    - meridian.meridian.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-meridian-meridian-io-v1-infra
  failurePolicy: Fail
  name: minfra.kb.io
  rules:
  - apiGroups:
    - meridian.meridian.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - infras
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-knode-alibabacloud-com-v1-machine
  failurePolicy: Fail
  name: mmachine.kb.io
  rules:
  - apiGroups:
    - knode.alibabacloud.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - machines
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-meridian-meridian-io-v1-cluster
  failurePolicy: Fail
  name: vcluster.kb.io
  rules:
  - apiGroups:
    - meridian.meridian.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-meridian-meridian-io-v1-infra
  failurePolicy: Fail
  name: vinfra.kb.io
  rules:
  - apiGroups:
    - meridian.meridian.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - infras
  sideEffects: None
