apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysqld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld
  labels:
    app: mysqld
spec:
  selector:
    matchLabels:
      app: mysqld
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqld
    spec:
      priorityClassName: system-cluster-critical
      tolerations:
        - operator: Exists
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      containers:
        - image: registry.{{.Region}}.aliyuncs.com/aoxn/mysql:{{.ImageVersion}}
          name: mysql
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account.owncloud
                  key: password
            - name: MYSQL_DATABASE
              value: aoxncloud
            - name: MYSQL_USER
              value: aoxn
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account.owncloud
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          resources:
            limits:
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 150Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          hostPath:
            path: /mnt/disk0/aoxn/application/mysqld/data/
            type: DirectoryOrCreate