# permissions for end users to view infras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: infra-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: meridian
    app.kubernetes.io/part-of: meridian
    app.kubernetes.io/managed-by: kustomize
  name: infra-viewer-role
rules:
- apiGroups:
  - meridian.meridian.io
  resources:
  - infras
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - meridian.meridian.io
  resources:
  - infras/status
  verbs:
  - get
