---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - meridian.meridian.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridian.meridian.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - meridian.meridian.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - meridian.meridian.io
  resources:
  - infras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridian.meridian.io
  resources:
  - infras/finalizers
  verbs:
  - update
- apiGroups:
  - meridian.meridian.io
  resources:
  - infras/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - meridian.meridian.io
  resources:
  - masters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridian.meridian.io
  resources:
  - masters/finalizers
  verbs:
  - update
- apiGroups:
  - meridian.meridian.io
  resources:
  - masters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - meridian.meridian.io
  resources:
  - mastersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridian.meridian.io
  resources:
  - mastersets/finalizers
  verbs:
  - update
- apiGroups:
  - meridian.meridian.io
  resources:
  - mastersets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - meridian.meridian.io
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridian.meridian.io
  resources:
  - tasks/finalizers
  verbs:
  - update
- apiGroups:
  - meridian.meridian.io
  resources:
  - tasks/status
  verbs:
  - get
  - patch
  - update
