---
apiVersion: v1
data:
  kubeconfig.conf: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: https://127.0.0.1:6443
        insecure-skip-tls-verify: true
      name: default
    contexts:
    - context:
        cluster: default
        namespace: default
        user: default
      name: default
    current-context: default
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
kind: ConfigMap
metadata:
  labels:
    app: kube-flannel-master
  name: kube-flannel-master
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-master-ds
  namespace: kube-system
  labels:
    tier: node
    app: flannel
spec:
  selector:
    matchLabels:
      tier: master
      app: flannel
  template:
    metadata:
      labels:
        tier: master
        app: flannel
    spec:
      tolerations:
        - operator: Exists
      serviceAccountName: flannel
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      containers:
        - name: kube-flannel
          image: registry.{{.Region}}.aliyuncs.com/acs/flannel:{{.ImageVersion}}
          command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr","--kubeconfig-file", "/config/flannel/kubeconfig.conf" ]
          securityContext:
            privileged: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: run
              mountPath: /run
            - name: kube-flannel-master
              mountPath: /config/flannel/
            - name: flannel-cfg
              mountPath: /etc/kube-flannel/
        - name: install-cni
          image: registry.{{.Region}}.aliyuncs.com/acs/flannel:{{.ImageVersion}}
          command: [ "/bin/sh", "-c", "set -e -x; cp -f /etc/kube-flannel/cni-conf.json /etc/cni/net.d/10-flannel.conf; while true; do sleep 3600; done" ]
          volumeMounts:
            - name: cni
              mountPath: /etc/cni/net.d
            - name: flannel-cfg
              mountPath: /etc/kube-flannel/
      volumes:
        - name: run
          hostPath:
            path: /run
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - configMap:
            defaultMode: 420
            name: kube-flannel-master
          name: kube-flannel-master
        - name: flannel-cfg
          configMap:
            name: kube-flannel-cfg