apiVersion: meridian.meridian.io/v1
kind: Infra
metadata:
  labels:
    app.kubernetes.io/name: infra
    app.kubernetes.io/instance: infra-sample
    app.kubernetes.io/part-of: meridian
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: meridian
  name: infra-sample
spec:
  # TODO(user): Add fields here
