# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/meridian.meridian.io_clusters.yaml
- bases/meridian.meridian.io_clusters.yaml
- bases/meridian.meridian.io_masters.yaml
- bases/meridian.meridian.io_clusters.yaml
- bases/meridian.meridian.io_mastersets.yaml
- bases/meridian.meridian.io_internalclusters.yaml
- bases/meridian.meridian.io_infras.yaml
- bases/meridian.meridian.io_tasks.yaml
- bases/meridian.meridian.io_requests.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- path: patches/webhook_in_clusters.yaml
- path: patches/webhook_in_masters.yaml
- path: patches/webhook_in_mastersets.yaml
#- path: patches/webhook_in_internalclusters.yaml
#- path: patches/webhook_in_infras.yaml
#- path: patches/webhook_in_tasks.yaml
#- path: patches/webhook_in_requests.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_clusters.yaml
#- path: patches/cainjection_in_masters.yaml
#- path: patches/cainjection_in_mastersets.yaml
#- path: patches/cainjection_in_internalclusters.yaml
#- path: patches/cainjection_in_infras.yaml
#- path: patches/cainjection_in_tasks.yaml
#- path: patches/cainjection_in_requests.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

configurations:
- kustomizeconfig.yaml
